import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { keccak256, type Hex } from "viem";
import { describe, expect, it } from "vitest";
import {
  assertCommitment,
  commitmentOf,
  commitmentStream,
  CONTAINER_TAG,
  CONTAINER_VERSION,
  ContainerError,
  SEED_WRAP_BYTES,
  MIN_CONTAINER_BYTES,
  type ContainerFault,
} from "../src/container.js";
import { jobIdOf } from "../src/orders.js";

/**
 * Container v1, driven through `test/vectors/container-v1.json`.
 *
 * **That file is a cross-repo contract, not a fixture of this suite.** The client
 * SDK assembles containers and the provider SDK splits them, each from the same
 * prose; three implementations written from one paragraph agree by luck, and a
 * disagreement surfaces as a job that strands with no visible cause. The vectors
 * are what make the agreement checkable. Plan 4 copies the file into the SDKs and
 * asserts against it there.
 *
 * These tests drive the file **both ways**: every positive case is recomputed
 * from its parts, and every negative case is pushed through the checker and must
 * produce the labelled fault. So the vectors cannot drift from the implementation
 * without one side or the other going red — which is the only thing that stops a
 * vector file from becoming decorative.
 *
 * The file was generated by this implementation and is asserted against here.
 * That is deliberate and it is not circular in the way that matters: what it
 * pins is not *"is keccak right"* but *"do three repositories split the same
 * bytes at the same offsets and hash them in the same order"*, and for that the
 * authority has to be one artifact rather than three readings of a sentence.
 */

interface Vectors {
  constants: {
    version: number;
    version_byte: Hex;
    wrap_bytes: number;
    min_container_bytes: number;
  };
  cases: {
    name: string;
    seed_wrap: Hex;
    ciphertext: Hex;
    container: Hex;
    ct_hash: Hex;
    c: Hex;
    owner: Hex;
    job_id: Hex;
  }[];
  wrap_swap: {
    ciphertext_from: string;
    seed_wrap_from: string;
    container: Hex;
    c: Hex;
    differs_from: Hex;
  };
  refusals: { name: string; fault: ContainerFault; container: Hex; c?: Hex }[];
}

const VECTORS_PATH = fileURLToPath(new URL("./vectors/container-v1.json", import.meta.url));
const vectors = JSON.parse(readFileSync(VECTORS_PATH, "utf8")) as Vectors;

const buf = (value: Hex): Buffer => Buffer.from(value.slice(2), "hex");

describe("container v1 — the constants the file and the code must agree on", () => {
  it("carries the version, its byte and the wrap width, and the code matches", () => {
    expect(CONTAINER_VERSION).toBe(vectors.constants.version);
    expect(`0x${CONTAINER_TAG.toString("hex")}`).toBe(vectors.constants.version_byte);
    expect(SEED_WRAP_BYTES).toBe(vectors.constants.wrap_bytes);
    expect(MIN_CONTAINER_BYTES).toBe(vectors.constants.min_container_bytes);
  });

  it("is one version byte, and the version is 0x01", () => {
    // Written out from the design rather than read from the constant, so a
    // changed version cannot agree with itself through the vectors file.
    //
    // The four-byte ASCII magic is gone (C2). It was diagnostic only: the
    // commitment check against the job id catches every case the magic caught,
    // and catches it harder, so a prefix no check depends on was decoration.
    // What is left is the discriminant — one byte, naming the wrap's kind and
    // its width together.
    expect(CONTAINER_VERSION).toBe(0x01);
    expect(CONTAINER_TAG).toEqual(Buffer.from([0x01]));
    expect(CONTAINER_TAG).toHaveLength(1);
    expect(MIN_CONTAINER_BYTES).toBe(81);
  });

  it("offers a case on both sides of a 32-byte boundary and an empty one", () => {
    // The vectors are only worth reading if they vary the thing that breaks.
    const lengths = vectors.cases.map((entry) => (entry.ciphertext.length - 2) / 2);
    expect(lengths).toContain(0);
    expect(lengths).toContain(31);
    expect(lengths).toContain(32);
    expect(lengths).toContain(33);
  });
});

describe("container v1 — every vector, recomputed", () => {
  it.each(vectors.cases.map((entry) => [entry.name, entry] as const))(
    "%s",
    (_name, entry) => {
      const container = buf(entry.container);
      const wrap = buf(entry.seed_wrap);
      const ciphertext = buf(entry.ciphertext);

      // The layout: the container really is those three pieces at those offsets.
      expect(container).toEqual(Buffer.concat([CONTAINER_TAG, wrap, ciphertext]));
      expect(wrap.length).toBe(SEED_WRAP_BYTES);

      // The two hashes, separately, so a wrong one is named.
      expect(keccak256(ciphertext as unknown as Uint8Array)).toBe(entry.ct_hash);
      expect(
        keccak256(
          Buffer.concat([
            CONTAINER_TAG,
            wrap,
            buf(entry.ct_hash),
          ]) as unknown as Uint8Array,
        ),
      ).toBe(entry.c);

      // And the shipped implementation, which is the point.
      expect(commitmentOf(container)).toBe(entry.c);
      expect(() => assertCommitment(container, entry.c)).not.toThrow();

      // The id the whole design turns on: a claimant re-derives exactly this from
      // the bytes it fetched and the owner on the job row.
      expect(jobIdOf(entry.owner as `0x${string}`, entry.c)).toBe(entry.job_id);
    },
  );

  it("gives every case a distinct commitment", () => {
    const seen = new Set(vectors.cases.map((entry) => entry.c));
    expect(seen.size).toBe(vectors.cases.length);
  });
});

describe("container v1 — streamed", () => {
  /**
   * The post door never holds a container whole: it hashes the bytes as they
   * stream in. The stream and the whole-buffer computation must agree on every
   * input, at every chunking — the head split across chunks, the ciphertext
   * arriving a byte at a time, the whole thing in one piece.
   */
  it.each(vectors.cases.map((entry) => [entry.name, entry] as const))(
    "%s, at every chunk size",
    (_name, entry) => {
      const container = buf(entry.container);
      for (const size of [1, 7, 80, 81, 82, 1024, container.length + 1]) {
        const stream = commitmentStream();
        for (let at = 0; at < container.length; at += size) {
          stream.update(container.subarray(at, at + size));
        }
        expect(stream.digest()).toBe(entry.c);
        expect(stream.bytes).toBe(container.length);
      }
    },
  );

  it("agrees with commitmentOf on a container far larger than any vector", () => {
    const container = Buffer.concat([
      CONTAINER_TAG,
      Buffer.alloc(SEED_WRAP_BYTES, 0xd4),
      Buffer.alloc(3 * 1024 * 1024 + 17, 0x61),
    ]);
    const stream = commitmentStream();
    for (let at = 0; at < container.length; at += 64 * 1024) {
      stream.update(container.subarray(at, at + 64 * 1024));
    }
    expect(stream.digest()).toBe(commitmentOf(container));
  });

  it("refuses a wrong version on the first byte, before the rest is read", () => {
    const stream = commitmentStream();
    const raised = (() => {
      try {
        stream.update(Buffer.from([0x02]));
        return null;
      } catch (error) {
        return error;
      }
    })();
    expect(raised).toBeInstanceOf(ContainerError);
    expect((raised as ContainerError).fault).toBe("bad_version");
  });

  it("refuses a container too short to split", () => {
    const stream = commitmentStream();
    stream.update(Buffer.concat([CONTAINER_TAG, Buffer.alloc(SEED_WRAP_BYTES - 1, 0xd1)]));
    const raised = (() => {
      try {
        stream.digest();
        return null;
      } catch (error) {
        return error;
      }
    })();
    expect(raised).toBeInstanceOf(ContainerError);
    expect((raised as ContainerError).fault).toBe("too_short");
  });
});

describe("container v1 — the wrap swap", () => {
  it("changes c, which is why the wrap is hashed in and not only the ciphertext", () => {
    const { wrap_swap: swap } = vectors;
    const donor = vectors.cases.find((entry) => entry.name === swap.seed_wrap_from);
    const source = vectors.cases.find((entry) => entry.name === swap.ciphertext_from);
    expect(donor).toBeDefined();
    expect(source).toBeDefined();

    // Assembled here from the two named cases rather than trusted from the file:
    // if the file's `container` were anything else this would fail.
    const swapped = Buffer.concat([
      CONTAINER_TAG,
      buf((donor as { seed_wrap: Hex }).seed_wrap),
      buf((source as { ciphertext: Hex }).ciphertext),
    ]);
    expect(`0x${swapped.toString("hex")}`).toBe(swap.container);

    expect(commitmentOf(swapped)).toBe(swap.c);
    // The load-bearing inequality. Identical ciphertext, another order's wrap,
    // and a commitment that cannot be mistaken for the first.
    expect(swap.c).not.toBe(swap.differs_from);
    expect((source as { c: Hex }).c).toBe(swap.differs_from);
  });
});

describe("container v1 — every refusal", () => {
  it.each(vectors.refusals.map((entry) => [entry.name, entry] as const))(
    "%s",
    (_name, entry) => {
      const container = buf(entry.container);
      let thrown: unknown;
      try {
        if (entry.c === undefined) commitmentOf(container);
        else assertCommitment(container, entry.c);
      } catch (error) {
        thrown = error;
      }
      expect(thrown).toBeInstanceOf(ContainerError);
      expect((thrown as ContainerError).fault).toBe(entry.fault);
    },
  );

  it("covers all three faults the checker can produce", () => {
    // A refusal list that lost a fault would let the guard for it be deleted with
    // nothing going red (R67).
    const faults = new Set(vectors.refusals.map((entry) => entry.fault));
    expect([...faults].sort()).toEqual(["bad_version", "commitment_mismatch", "too_short"]);
  });

  it("refuses one byte short of the split and accepts exactly at it", () => {
    // The boundary itself, probed at the edge rather than past it (R78): an
    // off-by-one here reads a wrap out of bounds and hashes a short slice.
    const atMinimum = Buffer.concat([CONTAINER_TAG, Buffer.alloc(SEED_WRAP_BYTES)]);
    expect(atMinimum.length).toBe(MIN_CONTAINER_BYTES);
    expect(() => commitmentOf(atMinimum)).not.toThrow();
    expect(() => commitmentOf(atMinimum.subarray(0, MIN_CONTAINER_BYTES - 1))).toThrow(
      ContainerError,
    );
  });
});
