/**
 * Every EIP-712 artifact this node verifies, against the contracts' own vectors.
 *
 * `test/vectors/signing-v3.json` is generated by
 * `vorq-evm-contracts/test/Vectors.t.sol`, which reproduces the devnet's
 * deterministic deployment in-process, derives each digest from the case's own
 * published payload, and hands every signature to the deployed contract, which
 * must accept it before a byte is written.
 *
 * This node declares **eleven** type tables across `orders.ts`, `api/routes/ops.ts`,
 * `asks/push.ts`, `escrow/release.ts` and `api/routes/auth.ts`, and until this file
 * existed none of them was checked against anything. A member renamed, retyped or
 * reordered in any of them makes `verifyTypedData` recover a stranger — the request
 * is refused, and nothing anywhere says why.
 *
 * Two assertions per artifact, and they are not the same assertion:
 *
 *  - the local table deep-equals the published one, which catches a drifted
 *    declaration even where no message in this file exercises every member;
 *  - the published signature recovers the published signer *through this node's
 *    own builder*, which proves the bytes it would verify are the bytes the
 *    deployed contract accepted.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  hashTypedData,
  recoverTypedDataAddress,
  type Address,
  type Hex,
  type TypedDataDomain,
} from "viem";

import { authorizationTypedData, EIP712_NAMES, orderTypedData } from "../src/orders.js";
import type { Addresses } from "../src/config.js";
import { OP_REGISTRY, OP_TYPES } from "../src/api/routes/ops.js";
import { ASK_SNAPSHOT_TYPES, askDomain, askSnapshotTypedData } from "../src/asks/push.js";
import { RELEASE_TYPES, releaseDomain } from "../src/escrow/release.js";
import { HANDOVER_AUTH_TYPES } from "../src/escrow/handover.js";
import { sessionDomain, SESSION_TYPES } from "../src/api/routes/auth.js";

interface Member {
  name: string;
  type: string;
}
interface Case {
  name: string;
  domain: string;
  typed_data: {
    types: Record<string, Member[]>;
    primaryType: string;
    domain: Record<string, unknown>;
    message: Record<string, any>;
  };
  digest: Hex;
  signer: Address;
  signature: Hex;
  extra?: Record<string, any>;
}

const VECTORS = JSON.parse(
  readFileSync(fileURLToPath(new URL("./vectors/signing-v3.json", import.meta.url)), "utf8"),
) as {
  chain_id: number;
  addresses: Record<string, Address>;
  domains: Record<string, { domain: Record<string, unknown>; separator: Hex | null }>;
  cases: Case[];
};

const CASES = new Map(VECTORS.cases.map((c) => [c.name, c]));
const A = VECTORS.addresses;

/**
 * The vectors' deployment as an {@link Addresses}, so the builders under test are
 * called the way the node calls them — through the address book, not through
 * loose arguments.
 *
 * `decimals` and `deployBlock` are along for the type: nothing a digest is built
 * over reads them.
 */
const ADDRESSES_FOR_VECTORS: Addresses = {
  chainId: VECTORS.chain_id,
  deployBlock: 0,
  jobRegistry: A.job_registry,
  providerRegistry: A.provider_registry,
  askRegistry: A.ask_registry,
  usdc: A.payment_token,
  decimals: 6,
  tokenDomain: { name: "USDC", version: "2" },
};

function vector(name: string): Case {
  const found = CASES.get(name);
  if (!found) throw new Error(`no vector named ${name}`);
  return found;
}

/**
 * A case's message with each member decoded according to its DECLARED type.
 *
 * JSON has one number type, so the file carries `uint128`/`uint256` as decimal
 * strings — a 256-bit value does not survive a double — and `bytes`/`bytes32` as
 * `0x` hex, which viem already takes verbatim. Driving the decode from the
 * `types` block rather than a hand-written field list is what keeps it from
 * drifting when a member changes.
 */
function decode(types: Record<string, Member[]>, primary: string, message: any): any {
  const out: Record<string, unknown> = {};
  for (const { name, type } of types[primary]) {
    const value = message[name];
    if (type.endsWith("[]")) {
      out[name] = value.map((e: unknown) => decode(types, type.slice(0, -2), e));
    } else if (types[type]) {
      out[name] = decode(types, type, value);
    } else if (/^uint(128|256)$/.test(type)) {
      out[name] = BigInt(value);
    } else {
      out[name] = value;
    }
  }
  return out;
}

function messageOf(name: string): any {
  const c = vector(name);
  return decode(c.typed_data.types, c.typed_data.primaryType, c.typed_data.message);
}

/** The published `types` block minus `EIP712Domain`, which no consumer declares. */
function publishedTypes(name: string): Record<string, Member[]> {
  const { EIP712Domain: _ignored, ...rest } = vector(name).typed_data.types;
  return rest;
}

/**
 * Assert a locally-built payload against a case, both ways.
 *
 * `types` is compared as plain JSON so a `readonly` `as const` table and the
 * file's mutable arrays compare by value rather than by variance.
 */
async function expectMatchesVector(
  name: string,
  built: { domain: TypedDataDomain; types: any; primaryType: string; message: any },
) {
  const c = vector(name);

  expect(JSON.parse(JSON.stringify(built.types))).toEqual(publishedTypes(name));
  expect(built.primaryType).toBe(c.typed_data.primaryType);
  expect(JSON.parse(JSON.stringify(built.domain))).toEqual(c.typed_data.domain);
  expect(hashTypedData(built as any)).toBe(c.digest);
  expect(await recoverTypedDataAddress({ ...(built as any), signature: c.signature })).toBe(
    c.signer,
  );
}

// ---------------------------------------------------------------------------
// the file itself
// ---------------------------------------------------------------------------

describe("the vectors belong to this deployment", () => {
  it("names the chain and the four addresses every digest was built over", () => {
    expect(VECTORS.chain_id).toBe(84532);
    for (const key of ["job_registry", "provider_registry", "ask_registry", "payment_token"]) {
      expect(A[key]).toMatch(/^0x[0-9a-fA-F]{40}$/);
    }
  });

  it("records a separator for every on-chain domain and none for the off-chain ones", () => {
    for (const key of ["job_registry", "provider_registry", "ask_registry", "payment_token"]) {
      expect(VECTORS.domains[key].separator).toMatch(/^0x[0-9a-f]{64}$/);
    }
    // Release and VorqSession have no contract to answer one; a null says so
    // rather than a zero word a consumer might compare against.
    for (const key of ["escrow", "session"]) {
      expect(VECTORS.domains[key].separator).toBeNull();
      expect(VECTORS.domains[key].domain).not.toHaveProperty("verifyingContract");
    }
  });

  it("is self-consistent: every case's payload hashes to its recorded digest", () => {
    for (const c of VECTORS.cases) {
      const built = {
        domain: c.typed_data.domain as TypedDataDomain,
        types: publishedTypes(c.name),
        primaryType: c.typed_data.primaryType,
        message: messageOf(c.name),
      };
      expect(hashTypedData(built as any), c.name).toBe(c.digest);
    }
  });
});

// ---------------------------------------------------------------------------
// orders.ts — Order and the payment authorization the escrow is pulled with
// ---------------------------------------------------------------------------

describe("orders.ts", () => {
  const termsOf = (name: string) => {
    const m = vector(name).typed_data.message;
    return {
      c: m.c as Hex,
      modelId: m.modelId,
      slaSecs: m.slaSecs,
      rateIn: BigInt(m.rateIn),
      rateOut: BigInt(m.rateOut),
      unitsIn: m.unitsIn,
      unitsOut: m.unitsOut,
      designated: m.designated,
      expiresAt: BigInt(m.expiresAt),
    };
  };

  it.each(["order-designated", "order-open"])("%s matches the vector", async (name) => {
    await expectMatchesVector(name, orderTypedData(VECTORS.chain_id, A.job_registry, termsOf(name) as any));
  });

  it("does not sign taskCid, which is why the vector carries one beside the message", () => {
    const built = orderTypedData(VECTORS.chain_id, A.job_registry, termsOf("order-designated") as any);
    expect(vector("order-designated").extra!.task_cid).toBeTruthy();
    expect(built.types.Order.map((m) => m.name)).not.toContain("taskCid");
    expect(Object.keys(built.message)).not.toContain("taskCid");
  });

  it("the payment authorization matches the vector", async () => {
    const m = vector("payment-authorization").typed_data.message;
    const d = vector("payment-authorization").typed_data.domain as { name: string; version: string };
    await expectMatchesVector(
      "payment-authorization",
      authorizationTypedData(
        { ...ADDRESSES_FOR_VECTORS, usdc: A.payment_token, tokenDomain: { name: d.name, version: d.version } },
        { from: m.from as Address, to: m.to as Address, value: BigInt(m.value),
          validBefore: BigInt(m.validBefore), jobId: m.nonce as Hex },
      ),
    );
  });

  it("the authorization is valid through expires_at and its nonce is the job id", () => {
    const m = vector("payment-authorization").typed_data.message;
    expect(m.validAfter).toBe("0");
    expect(m.nonce).toBe(vector("payment-authorization").extra!.job_id);
  });
});

// ---------------------------------------------------------------------------
// api/routes/ops.ts — the five provider ops, over two registry domains
// ---------------------------------------------------------------------------

describe("api/routes/ops.ts", () => {
  const opDomain = (registry: "job" | "provider", chainId: number, verifyingContract: Address) =>
    ({ name: EIP712_NAMES[registry], version: "2", chainId, verifyingContract }) as const;

  const registryAddress = (primary: keyof typeof OP_REGISTRY) =>
    OP_REGISTRY[primary] === "job" ? A.job_registry : A.provider_registry;

  const OP_CASES: Array<[string, keyof typeof OP_TYPES]> = [
    ["claim", "Claim"],
    ["settle", "Settle"],
    ["fail", "Fail"],
    ["set-identity", "SetIdentity"],
    ["set-identity-empty-evidence", "SetIdentity"],
    ["request-capacity", "RequestCapacity"],
  ];

  it.each(OP_CASES)("%s matches the vector", async (name, primary) => {
    await expectMatchesVector(name, {
      domain: opDomain(OP_REGISTRY[primary], VECTORS.chain_id, registryAddress(primary)),
      types: OP_TYPES[primary],
      primaryType: primary,
      message: messageOf(name),
    });
  });

  it("routes each op to the registry the vector signed it against", () => {
    for (const [name, primary] of OP_CASES) {
      expect(vector(name).typed_data.domain.verifyingContract, name).toBe(registryAddress(primary));
    }
  });

  it("Claim and Fail share their members and differ only by type name", () => {
    expect(OP_TYPES.Claim.Claim).toEqual(OP_TYPES.Fail.Fail);
    expect(vector("claim").typed_data.message).toEqual(vector("fail").typed_data.message);
    // ...and that alone is enough to make the digests differ. No table comparison
    // can catch a signer that reuses one type for the other; only this can.
    expect(vector("claim").digest).not.toBe(vector("fail").digest);
  });

  it("Settle attests a count and names no result CID", () => {
    expect(OP_TYPES.Settle.Settle.map((m) => m.name)).toEqual([
      "jobId",
      "completionTok",
      "issuedAt",
    ]);
    for (const table of Object.values(OP_TYPES)) {
      for (const members of Object.values(table) as readonly Member[][]) {
        expect(members.some((m: Member) => m.name.toLowerCase().includes("cid"))).toBe(false);
      }
    }
  });

  it("empty evidence hashes rather than zero-padding", async () => {
    expect(vector("set-identity-empty-evidence").typed_data.message.evidence).toBe("0x");
    expect(vector("set-identity").digest).not.toBe(vector("set-identity-empty-evidence").digest);
  });
});

// ---------------------------------------------------------------------------
// asks/push.ts — the third registry domain
// ---------------------------------------------------------------------------

describe("asks/push.ts", () => {
  /**
   * The vector's snapshot in the shape `quotes_live` stores it: every member a
   * decimal string, which `askSnapshotTypedData` converts exactly once.
   */
  const snapshotOf = (name: string) => {
    const m = vector(name).typed_data.message;
    return {
      provider_id: String(m.providerId),
      signed_at: String(m.signedAt),
      quotes: m.quotes.map((q: any) => ({
        model_id: String(q.modelId),
        sla: String(q.sla),
        rate_in: String(q.rateIn),
        rate_out: String(q.rateOut),
      })),
    };
  };

  it.each(["ask-snapshot", "ask-snapshot-empty"])("%s matches the vector", async (name) => {
    await expectMatchesVector(
      name,
      askSnapshotTypedData(snapshotOf(name) as any, VECTORS.chain_id, A.ask_registry),
    );
  });

  it("declares Ask as a referenced struct of AskSnapshot", () => {
    expect(ASK_SNAPSHOT_TYPES).toEqual(publishedTypes("ask-snapshot"));
    expect(ASK_SNAPSHOT_TYPES.AskSnapshot.find((m) => m.name === "quotes")?.type).toBe("Ask[]");
  });

  it("signs against the ask registry and neither other VORQ domain", () => {
    const d = askDomain(VECTORS.chain_id, A.ask_registry);
    expect(d.verifyingContract).toBe(A.ask_registry);
    expect(d.verifyingContract).not.toBe(A.job_registry);
    expect(d.verifyingContract).not.toBe(A.provider_registry);
  });

  it("carries a withdrawal inside the signed snapshot", () => {
    // `setAsks` upserts: a slot the snapshot omits keeps its old price forever,
    // and only `rateOut == 0` deletes one. So the withdrawal has to be signed.
    const quotes = messageOf("ask-snapshot").quotes;
    expect(quotes.some((q: any) => q.rateOut === 0n)).toBe(true);
  });

  it("signs an empty book, because keccak256 of no element hashes is a real value", () => {
    expect(messageOf("ask-snapshot-empty").quotes).toEqual([]);
    expect(vector("ask-snapshot-empty").digest).not.toBe(vector("ask-snapshot").digest);
  });
});

// ---------------------------------------------------------------------------
// escrow/release.ts and api/routes/auth.ts — the two artifacts no contract verifies
// ---------------------------------------------------------------------------

describe("the off-chain artifacts", () => {
  it("Release matches the vector", async () => {
    await expectMatchesVector("release", {
      domain: releaseDomain(VECTORS.chain_id),
      types: RELEASE_TYPES,
      primaryType: "Release",
      message: messageOf("release"),
    });
  });

  it("Release binds the response key, which is what makes a replay harmless", () => {
    expect(RELEASE_TYPES.Release.map((m) => m.name)).toContain("responsePubkey");
  });

  /**
   * `HandoverAuth` has the sharpest cross-language risk of the three: both ends
   * are coordinator instances, so a divergence surfaces as two of *our own*
   * processes refusing each other during an upgrade — the moment least able to
   * absorb it, and the one where the successor is holding no keys yet.
   */
  it("HandoverAuth matches the vector", async () => {
    await expectMatchesVector("handover-auth", {
      domain: releaseDomain(VECTORS.chain_id),
      types: HANDOVER_AUTH_TYPES,
      primaryType: "HandoverAuth",
      message: messageOf("handover-auth"),
    });
  });

  /**
   * The signature covers the whole request. `channelPubkey` binds it to one
   * exchange — without it a captured authorization pulls the key set to any
   * channel the captor likes — and `issuedAt` bounds the capture's usefulness to
   * the same ±600 s the release path uses.
   */
  it("HandoverAuth binds the channel key and the clock, and nothing else", () => {
    expect(HANDOVER_AUTH_TYPES.HandoverAuth.map((m) => m.name)).toEqual([
      "channelPubkey",
      "issuedAt",
    ]);
  });

  /**
   * `HandoverAuth` and `Release` share the escrow domain, which is safe only
   * because their type hashes differ — EIP-712 mixes the primary type into the
   * digest. Asserted rather than assumed: this is the property that would break
   * silently if someone gave `HandoverAuth` the same member list as some future
   * sibling.
   */
  it("does not collide with Release despite sharing the escrow domain", () => {
    expect(vector("handover-auth").digest).not.toBe(vector("release").digest);
    expect(vector("handover-auth").domain).toBe(vector("release").domain);
  });

  it("VorqSession matches the vector", async () => {
    await expectMatchesVector("session", {
      domain: sessionDomain(VECTORS.chain_id),
      types: SESSION_TYPES,
      primaryType: "VorqSession",
      message: messageOf("session"),
    });
  });

  it("binds the session domain to the deployment's chain, as a browser wallet demands", () => {
    expect(sessionDomain(VECTORS.chain_id).chainId).toBe(VECTORS.chain_id);
    expect(vector("session").typed_data.domain.chainId).toBe(VECTORS.chain_id);
  });

  it("keeps the session in a namespace the chain will never accept", () => {
    expect(sessionDomain(VECTORS.chain_id).version).toBe("1");
    expect(sessionDomain(VECTORS.chain_id)).not.toHaveProperty("verifyingContract");
    // version 2 is every on-chain artifact's, so a captured login cannot be
    // replayed as an op
    expect(vector("claim").typed_data.domain.version).toBe("2");
  });
});
