// GENERATED by scripts/gen-abi.sh — do not edit by hand.
// Source: vorq-evm-contracts/out/AskRegistry.sol/AskRegistry.json (14 entries)

export const askRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "registry_",
        "type": "address",
        "internalType": "contract ProviderRegistry"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ASK_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DOMAIN_SEPARATOR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "EIP712_NAME",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "EIP712_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_QUOTES",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SNAPSHOT_TYPEHASH",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "eip712Domain",
    "inputs": [],
    "outputs": [
      {
        "name": "fields",
        "type": "bytes1",
        "internalType": "bytes1"
      },
      {
        "name": "name",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "version",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "chainId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "verifyingContract",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "salt",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "extensions",
        "type": "uint256[]",
        "internalType": "uint256[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getQuote",
    "inputs": [
      {
        "name": "providerId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "modelId",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "sla",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "rateIn",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "rateOut",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "lastSignedAt",
    "inputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "registry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ProviderRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setAsks",
    "inputs": [
      {
        "name": "batch",
        "type": "tuple[]",
        "internalType": "struct AskSnapshot[]",
        "components": [
          {
            "name": "providerId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "signedAt",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "quotes",
            "type": "tuple[]",
            "internalType": "struct Ask[]",
            "components": [
              {
                "name": "modelId",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "sla",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "rateIn",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "rateOut",
                "type": "uint128",
                "internalType": "uint128"
              }
            ]
          }
        ]
      },
      {
        "name": "sigs",
        "type": "bytes[]",
        "internalType": "bytes[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "AsksPublished",
    "inputs": [
      {
        "name": "providerId",
        "type": "uint32",
        "indexed": true,
        "internalType": "uint32"
      },
      {
        "name": "signedAt",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "quotes",
        "type": "tuple[]",
        "indexed": false,
        "internalType": "struct Ask[]",
        "components": [
          {
            "name": "modelId",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "sla",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "rateIn",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "rateOut",
            "type": "uint128",
            "internalType": "uint128"
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "LengthMismatch",
    "inputs": []
  }
] as const;
