#!/usr/bin/env bash
#
# Vendors the three VORQ contract ABIs from the contracts repo's forge build
# output into src/abi/*.ts. The generated files are committed, so this repo and
# CI build with no contracts checkout present.
#
# Artifacts are named ONE BY ONE, never globbed. out/JobRegistry.sol/ holds
# IERC20.json beside JobRegistry.json, and out/<Name>.sol/*.json would vendor
# whichever sorted last — silently, with no build error, so every decode fails
# later at runtime. The entry-count assertions below are the second lock on that.
#
# Every path is quoted: this repo lives under a path containing spaces.
#
# Usage: ./scripts/gen-abi.sh   [CONTRACTS_DIR=../vorq-evm-contracts]
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
CONTRACTS="${CONTRACTS_DIR:-${ROOT}/../vorq-evm-contracts}"
OUT_DIR="${ROOT}/src/abi"

# <export prefix>|<artifact path, relative to the contracts repo>|<expected ABI entries>
SPECS=(
  "jobRegistry|out/JobRegistry.sol/JobRegistry.json|69"
  "providerRegistry|out/ProviderRegistry.sol/ProviderRegistry.json|55"
  "askRegistry|out/AskRegistry.sol/AskRegistry.json|14"
)

if [ ! -d "${CONTRACTS}" ]; then
  echo "gen-abi: contracts repo not found at ${CONTRACTS}" >&2
  echo "gen-abi: set CONTRACTS_DIR to its path" >&2
  exit 1
fi

mkdir -p "${OUT_DIR}"

for spec in "${SPECS[@]}"; do
  name="${spec%%|*}"
  rest="${spec#*|}"
  artifact="${rest%%|*}"
  expected="${rest##*|}"
  src="${CONTRACTS}/${artifact}"

  if [ ! -f "${src}" ]; then
    echo "gen-abi: missing artifact ${src}" >&2
    echo "gen-abi: run 'forge build' in the contracts repo first" >&2
    exit 1
  fi

  node -e '
    const fs = require("node:fs");
    const [src, dest, name, artifact, expected] = process.argv.slice(1);

    const abi = JSON.parse(fs.readFileSync(src, "utf8")).abi;
    if (!Array.isArray(abi)) {
      console.error(`gen-abi: ${artifact} has no abi array`);
      process.exit(1);
    }
    if (abi.length !== Number(expected)) {
      console.error(
        `gen-abi: ${artifact} has ${abi.length} ABI entries, expected ${expected}. ` +
        "Either the wrong artifact was read or the contract changed; the contracts " +
        "are frozen, so check the artifact path before touching the expected count."
      );
      process.exit(1);
    }

    fs.writeFileSync(
      dest,
      `// GENERATED by scripts/gen-abi.sh — do not edit by hand.\n` +
      `// Source: vorq-evm-contracts/${artifact} (${abi.length} entries)\n\n` +
      `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`
    );
    console.log(`gen-abi: ${name}Abi <- ${artifact} (${abi.length} entries)`);
  ' "${src}" "${OUT_DIR}/${name}.ts" "${name}" "${artifact}" "${expected}"
done
